resolver: nightly-2021-08-20

packages:
- '.'

extra-deps:
- git: https://github.com/viercc/trie-simple.git
  commit: c26524381311c6f546c6d44ef82b37e9a10fa930

flags: {}

extra-package-dbs: []

system-ghc: true
